wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1676715389.47027
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.10.6
      5: 0.13.10
      6: 4.26.0
      8:
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 1
lr:
  desc: null
  value: 1.0e-05
max_length:
  desc: null
  value: 128
max_obs:
  desc: null
  value: 500000
model_name:
  desc: null
  value: distilbert-base-uncased
